config/routes.rb
Rails.application.routes.draw do
  root to: 'todo_lists#index'

  resources :todo_lists, only: [:index, :show, :new, :create], shallow: true do
    resources :tasks, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo_list

  validates :description, presence: true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user

  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :todo_lists, dependent: :destroy

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new(todo_list_id: params[:todo_list_id])
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to todo_list_path(params[:todo_list_id])
      flash[:notice] = 'New task was added'
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  private

  def task_params
    params.
      require(:task).
      permit(
        :description,
        :expires_at,
      ).merge(
      todo_list_id: params[:todo_list_id],
    )
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    if current_user.present?
      @todo_lists = current_user.todo_lists.includes(:tasks)
    else
      TodoList.none
    end
  end

  def show
    @todo_list = TodoList.find(params[:id])
  end

  def new
    @todo_list = current_user.todo_lists.new
  end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    if @todo_list.save
      redirect_to action: :show, id: @todo_list.id
      flash[:notice] = 'New todo list successfully created'
    else
      flash[:error] = 'Error'
      render :new
    end
  end

  private

  def todo_list_params
    params.
      require(:todo_list).
      permit(
        :title,
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Todo_Rails', root_path, class: 'navbar-brand' %>

    <div class="signed">
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= button_to 'Sign in', sign_in_path %>
      <% end %>
    </div>
  </nav>

  <div class="container">

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </div>
  </body>
</html>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(:task, url: todo_list_tasks_path(todo_list_id: params[:todo_list_id])) do |f| %>
  <div class="title ">
    <%= f.label :description %>
    <%= f.text_field(:description) %>
  </div>
  <div class="title ">
    <%= f.label :expires_at %>
    <%= f.datetime_select(:expires_at, class: 'datetimepicker') %>
  </div>
  <div class="submit">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/todo_lists/index.html.erb
<% if current_user %>
  <h1>Your todo lists
    <%=link_to 'New Todo', new_todo_list_path, class: 'btn btn-primary' %>
  </h1>
<% end %>

<ul class="list-group">
  <% @todo_lists&.each do |todo_list| %>
    <% if todo_list.title.present? %>
      <li class="list-group-item">
        <%= link_to todo_list.title, todo_list_path(todo_list) %>
        <ul class="list-group">
          <% todo_list.tasks&.each do |task| %>
            <li class="list-group-item">
              <%= task.description %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/todo_lists/new.html.erb
<h1>New todo list</h1>

    <div class="title ">
    </div>
  <div class="submit">
  </div>
<%= form_for(@todo_list) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control') %>
  </div>
  <%= f.submit 'Save' %>
<% end %>

app/views/todo_lists/show.html.erb
<% if @todo_list.present? %>
  <%= link_to 'Create new task', new_todo_list_task_path(todo_list_id: @todo_list.id), class: 'btn btn-primary' %>
  <div>
    <h2>
      <%= @todo_list.title %>
    </h2>
    <ul class="list-group">
      <% @todo_list.tasks&.each do |task| %>
        <li class="list-group-item">
          <%= task.description %>
          <div>
            <small>
              Expires at: <%= task.expires_at %>
            </small>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>